"""A self-contained sample migration, for seeing the whole pipeline run.

No v2 login and no production writes: this seeds a small local database shaped
like harvested v2 customers, and a starter mapping that writes them to v3's
`/api/V1/customers`. Point v3 at the local mock, run it, and watch customers
flow source → transform → mock, then browse them and roll back.

The rows are obviously fake. The mapping is a real, minimal mapping — the same
shape you would write for the real migration — so the sample doubles as a
worked example.
"""

from __future__ import annotations

import sqlite3
from pathlib import Path

from .mockv3 import seed as mock_seed

SAMPLE_DB = "sample.sqlite"
SAMPLE_MAPPING = "mapping.sample.yaml"

# Shaped like the customer_details collection in config/harvest.eag-v2.yaml, so
# the mapping below is representative of the real one.
_DDL = """
CREATE TABLE customers (
    id             INTEGER PRIMARY KEY,
    full_name      TEXT,
    first_name     TEXT,
    last_name      TEXT,
    email          TEXT,
    phone          TEXT,
    city           TEXT,
    state          TEXT,
    zip            TEXT,
    account_number TEXT
);
"""

_ROWS = [
    (1, "Dana Reyes", "Dana", "Reyes", "dana@example.com", "(555) 123-4567",
     "San Francisco", "CA", "94107", None),
    (2, "Sam Oyelaran", "Sam", "Oyelaran", "sam.oyelaran@example.com", "555-987-6543",
     "San Francisco", "CA", "94107", "ACCT-2201"),
    (3, "Kit Nakamura", "Kit", "Nakamura", "kit@example.org", "5551112222",
     "New York", "NY", "10001", None),
    (4, "Robin Vale", "Robin", "Vale", "robin@example.net", "555-444-3333",
     "Chicago", "IL", "60601", None),
    (5, "Ash Whitfield", "Ash", "Whitfield", "ash@example.com", "5559990000",
     "Atlanta", "GA", "30301", "ACCT-5511"),
]

# A real, minimal mapping. customerType and pricingProfile are the two values a
# customer cannot be created without; pricingProfile is a foreign key to v3's
# reference data, so it is a const pointing at the mock's Default profile. For
# the real migration, swap that UUID for the one `eagm v3-snapshot` records.
_MAPPING = f"""\
# A starter mapping for the sample migration (customers → v3's HTTP API).
# Generated by `eagm sample`. Edit freely — this is an ordinary mapping.
version: 1
defaults:
  batch_size: 5
  on_error: record
entities:
  - name: customers
    source:
      table: customers
      key: id
    target:
      # No table to introspect over HTTP — the endpoint is the target.
      table: customers
      endpoint: /api/V1/customers
      key: id
      conflict: skip
    fields:
      - to: customerName
        from: full_name
        transform: [trim]
        required: true
      - to: phoneNumber
        from: phone
        transform: [phone]
      - to: email
        from: email
        transform: [trim, email]
      - to: externalAccountingId
        from: account_number
      # Cash — the one customerType code the survey confirmed.
      - to: customerType
        const: 9
      # Foreign key to v3's reference data. This is the mock's Default pricing
      # profile; snapshot real v3 and use its real UUID for production.
      - to: pricingProfile
        const: "{mock_seed.PP_DEFAULT}"
"""


def create(state_dir: Path, config_dir: Path) -> dict[str, Path]:
    """Write the sample database and mapping. Returns the paths."""
    state_dir.mkdir(parents=True, exist_ok=True)
    config_dir.mkdir(parents=True, exist_ok=True)

    db_path = state_dir / SAMPLE_DB
    if db_path.exists():
        db_path.unlink()
    conn = sqlite3.connect(db_path)
    with conn:
        conn.executescript(_DDL)
        conn.executemany(
            "INSERT INTO customers VALUES (?,?,?,?,?,?,?,?,?,?)", _ROWS
        )
    conn.close()

    mapping_path = config_dir / SAMPLE_MAPPING
    mapping_path.write_text(_MAPPING, encoding="utf-8")
    return {"db": db_path, "mapping": mapping_path, "rows": len(_ROWS)}


def db_url(state_dir: Path) -> str:
    """The V2_DATABASE_URL the sample uses, in container-path form."""
    return "sqlite:////app/state/" + SAMPLE_DB
